### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by Donwaztok** [ducke-consultoria/vscode-ducke-theme#1]
![image](https://github.com/ducke-consultoria/vscode-ducke-theme/assets/25177825/d13ed2e9-a5f7-43c6-95d0-182a702b8c87)

![image](https://github.com/ducke-consultoria/vscode-ducke-theme/assets/25177825/3f219fce-131a-4d0c-8298-ae52fff5e136)

![image](https://github.com/ducke-consultoria/vscode-ducke-theme/assets/25177825/a16f351b-bda4-42ad-906d-135b1fe6987a)

![image](https://github.com/ducke-consultoria/vscode-ducke-theme/assets/25177825/ce682be6-358f-45c7-96b1-f8f6f9ad4b41)

![image](https://github.com/ducke-consultoria/vscode-ducke-theme/assets/25177825/03073fec-d9d5-4fbd-903e-b238d9c2b59d)

![image](https://github.com/ducke-consultoria/vscode-ducke-theme/assets/25177825/a6beb0c5-dfa0-42e7-9bf2-2551dc269871)

**Comment by raphazappa** [comment]
![image](https://github.com/ducke-consultoria/vscode-ducke-theme/assets/40356907/9263cc93-3696-4a02-b2c7-fef6c7131d6c)

**Comment by Donwaztok** [comment]
Scrollbar needs transparency
![image](https://github.com/ducke-consultoria/vscode-ducke-theme/assets/25177825/f290b28c-ad1c-456e-bead-8e59e1638594)

**Comment by Donwaztok** [comment]
Remove bar border
![image](https://github.com/ducke-consultoria/vscode-ducke-theme/assets/25177825/a9c5176b-7d2f-48fa-b04e-ee1939fc80fa)

**Comment by Donwaztok** [comment]
Errors not showing
![image](https://github.com/ducke-consultoria/vscode-ducke-theme/assets/25177825/6edb36e7-d1d2-461a-aafa-1ff0e2a7bb40)
